
db.host=localhost
db.port=3306
db.name=student_library_system
db.username=root
db.password=leraa
db.driver=com.mysql.cj.jdbc.Driver


db.maxPoolSize=10
db.minPoolSize=2
db.connectionTimeout=30000
db.idleTimeout=600000
db.maxLifetime=1800000


db.useSSL=false
db.allowPublicKeyRetrieval=true
db.serverTimezone=UTC